spring.application.name=cyberthreatplatform

spring.datasource.url=jdbc:mysql://localhost:3306/cyberthreatdb
spring.datasource.username=root
spring.datasource.password=@Vradhich123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080